#!/bin/bash
#找出java的进程ID
javaId=`pgrep java`
#找出java进程中最消耗cpu的线程ID
topJavaId=`top -b -n 1 -Hp ${javaId}|grep java|head -n 1|awk '{print $1}'`
#将最耗cpu的java线程ID转换为16进制
topJavaId16=`printf "%x" ${topJavaId}`
#定位最耗cpu的线程位置
jstack ${javaId}|grep ${topJavaId16}
